<table width="100%" bgcolor="#f0f2ea" cellpadding="0" cellspacing="0" border="0">
    <tbody>
    <tr>
        <td style="padding: 40px 0;"><!-- begin main block -->
            <table cellpadding="0" cellspacing="0" width="608" border="0" align="center">
                <tbody>
                <tr>
                    <td><a href="//pixelbuddha.net/" style="display: block; width: 407px; height: 100px; margin: 0 auto 30px;"> <img src="//cl.ly/image/1r3y0x190q0r/logo.png" width="407" height="100" alt="Pixelbuddha" style="display: block; border: 0; margin: 0;" /> </a>
                        <p style="margin: 0 0 36px; text-align: center; font-size: 14px; line-height: 20px; text-transform: uppercase; color: #626658;">what is the most fascinating thing about summer?</p>
                        <!-- begin wrapper -->
                        <table cellpadding="0" cellspacing="0" border="0" width="100%">
                            <tbody>
                            <tr>
                                <td width="8" height="4" colspan="2">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>WHAT IS THE MOST FASCINATING THING ABOUT SUMMER
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td width="8" height="4" colspan="2">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                            </tr>
                            <tr>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td colspan="3" rowspan="3" bgcolor="#FFFFFF" style="padding: 0 0 30px;"><!-- begin content --> <img src="//cl.ly/image/1n1x3x0C3U00/header.jpg" width="600" height="400" alt="summer&lsquo;s coming trimm your sheeps" style="display: block; border: 0; margin: 0 0 44px; background: #eeeeee;" />
                                    <p style="margin: 0 30px 33px; ; text-align: center; text-transform: uppercase; font-size: 24px; line-height: 30px; font-weight: bold; color: #484a42;">Best articles in this month</p>
                                    <!-- begin articles -->
                                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                        <tbody>
                                        <tr valign="top">
                                            <td width="30">
                                                <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                            </td>
                                            <td><a style="display: block; margin: 0 0 14px;" href="//pixelbuddha.net/"><img src="//cl.ly/image/3U3E092x3I0k/article.jpg" width="255" height="150" alt="More" style="display: block; margin: 0; border: 0; background: #eeeeee;" /></a>
                                                <p style="font-size: 14px; line-height: 22px; font-weight: bold; color: #333333; margin: 0 0 5px;"><a href="//pixelbuddha.net/" style="color: #6c7e44; text-decoration: none;">What is it like to be young and free minded in North Korea</a></p>
                                                <p style="margin: 0 0 35px; font-size: 12px; line-height: 18px; color: #333333;">Fusce amet ligula ornare tempus vulputate ipsum semper. Praesent non lorem odio. Fusce sed dui massa, eu viverra erat.</p>
                                            </td>
                                            <td width="30">
                                                <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                            </td>
                                            <td><a style="display: block; margin: 0 0 14px;" href="//pixelbuddha.net/"><img src="//cl.ly/image/2u2V0M1D0s0R/article2.jpg" width="255" height="150" alt="More" style="display: block; margin: 0; border: 0; background: #eeeeee;" /></a>
                                                <p style="font-size: 14px; line-height: 22px; font-weight: bold; color: #333333; margin: 0 0 5px;"><a href="//pixelbuddha.net/" style="color: #6c7e44; text-decoration: none;">What is it like to be young and free minded in North Korea</a></p>
                                                <p style="margin: 0 0 35px; font-size: 12px; line-height: 18px; color: #333333;">Fusce amet ligula ornare tempus vulputate ipsum semper. Praesent non lorem odio. Fusce sed dui massa, eu viverra erat.</p>
                                            </td>
                                            <td width="30">
                                                <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                            </td>
                                        </tr>
                                        <tr valign="top">
                                            <td width="30">
                                                <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                            </td>
                                            <td colspan="3"><a style="display: block; margin: 0 0 14px;" href="//pixelbuddha.net/"><img src="//cl.ly/image/17321J0D3i0z/full.jpg" width="540" height="220" alt="More" style="display: block; margin: 0; border: 0; background: #eeeeee;" /></a>
                                                <p style="font-size: 14px; line-height: 22px; font-weight: bold; color: #333333; margin: 0 0 5px;"><a href="//pixelbuddha.net/" style="color: #6c7e44; text-decoration: none;">What is it like to be young and free minded in North Korea</a></p>
                                                <p style="margin: 0 0 35px; font-size: 12px; line-height: 18px; color: #333333;">Fusce amet ligula ornare tempus vulputate ipsum semper. Praesent non lorem odio. Fusce sed dui massa, eu viverra erat.</p>
                                            </td>
                                            <td width="30">
                                                <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <!-- /end articles -->
                                    <p style="margin: 0 30px 29px; border-top: 2px solid #e5e5e5; font-size: 5px; line-height: 5px;"><br /><br /></p>
                                    <!-- end content --></td>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                            </tr>
                            <tr>
                                <td width="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td width="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                            </tr>
                            <tr>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                            </tr>
                            <tr>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                                <td width="4" height="4">
                                    <p style="margin: 0; font-size: 1px; line-height: 1px;">&nbsp;</p>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        <!-- end wrapper--></td>
                </tr>
                </tbody>
            </table>
            <!-- end main block --></td>
    </tr>
    </tbody>
</table>